---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: demo-secret
  namespace: demo 
spec:
  encryptedData:
    password: AgBUzbNKrxJbA9p1mJ4uAGZLCOZGPvjZ+vjR4Mnodu7fmCVWRVWzk3BYJR8QW9b5Dr/9Vv/3I0idfBl08i/TWN9YXYj9lFaM8IAsUkJCZjTJssRSPqONmaWp4hB4IcOOKiur497o3aCWUBN+8XB4QiDHuyf2v5dIqRV87ij/E96wF+U7B/DzxETaNaLmembrWcHlQzaN4Bx287cCDMSZZf/u2Iv/cXpvJxSIb+5AuXcYfrxuUvah5RUm93bcfoQ/Cwd3rrccuj+9SW12Vr0LgjHvLhX2uuZn3jrtgNUD2hS1BBxtqOpakKev4A1dhY1qQ0EMxG+7wlwIXVa8SXeXT/CCoUPQPujccVJqIsy464cqxv+zeR28Jz7J8/tRogrWxBvE8MvoCvbXo2tcHE1yf3APPqigoTDG8DSmLh32Vdp6Lxa5/dMpY1EhoVmqNeKryacRh+oImVsuxnnW1aytpSLNZ7gjkR6qv7K/7tzxR7/BL55od9SDVQ1Xa1c79WLf3/VQAO0EyF5t4oQkDuy1c7eazZlgbcHaizsat6XB4WuA2EyDgkW2tL/+ZcTZMUkwyYW/VMV5adtVXP2TTSM1L2IDmnUQjGIo6L4iN2PaDVtOojUkFwzaEKTRsB5uNd2znMOF2vX6BSabSHCcCKhA7Ah3nGPWiSXTfb9ZNJgwkpdnJ0nuwQ3rZBWody45JvUD54ow2SODzSpd2g==
  template:
    metadata:
      creationTimestamp: null
      name: demo-secret
      namespace: default
    type: Opaque
